@echo off
echo.
echo ====================================================
echo    MuMuDVB Web Panel - Instalacija i Setup
echo ====================================================
echo.

REM Proveri da li je Node.js instaliran
node --version >nul 2>&1
if %errorlevel% neq 0 (
    echo GREŠKA: Node.js nije instaliran!
    echo Molimo instalirajte Node.js sa https://nodejs.org/
    echo.
    pause
    exit /b 1
)

echo ✓ Node.js je instaliran
node --version

REM Proveri da li je npm dostupan
npm --version >nul 2>&1
if %errorlevel% neq 0 (
    echo GREŠKA: npm nije dostupan!
    pause
    exit /b 1
)

echo ✓ npm je dostupan
npm --version
echo.

REM Instaliraj npm pakete
echo Instaliranje npm paketa...
echo.
call npm install

if %errorlevel% neq 0 (
    echo.
    echo GREŠKA: Instalacija npm paketa neuspešna!
    pause
    exit /b 1
)

echo.
echo ✓ npm paketi uspešno instalirani
echo.

REM Kreiraj osnovne direktorijume
if not exist "configs" mkdir configs
if not exist "logs" mkdir logs
if not exist "temp" mkdir temp

echo ✓ Direktorijumi kreirani
echo.

REM Kreiranje sample konfiguracije
echo # MuMuDVB Sample Configuration > configs\sample.conf
echo # Generated by Web Panel >> configs\sample.conf
echo. >> configs\sample.conf
echo # Basic DVB settings >> configs\sample.conf
echo card=0 >> configs\sample.conf
echo freq=11296 >> configs\sample.conf
echo pol=h >> configs\sample.conf
echo srate=27500 >> configs\sample.conf
echo. >> configs\sample.conf
echo # Autoconfiguration >> configs\sample.conf
echo autoconfiguration=full >> configs\sample.conf
echo. >> configs\sample.conf
echo # Network settings >> configs\sample.conf
echo multicast_ttl=2 >> configs\sample.conf
echo unicast=1 >> configs\sample.conf
echo port_http=4242 >> configs\sample.conf
echo. >> configs\sample.conf
echo # SAP announces >> configs\sample.conf
echo sap=1 >> configs\sample.conf
echo. >> configs\sample.conf
echo # Stream rewriting >> configs\sample.conf
echo rewrite_pat=1 >> configs\sample.conf
echo rewrite_sdt=1 >> configs\sample.conf
echo sort_eit=1 >> configs\sample.conf

echo ✓ Sample konfiguracija kreirana
echo.

echo ====================================================
echo              INSTALACIJA ZAVRŠENA!
echo ====================================================
echo.
echo Za pokretanje web panel-a koristite:
echo.
echo    npm start
echo.
echo Web panel će biti dostupan na:
echo    http://localhost:8080
echo.
echo WebSocket server će biti na:
echo    ws://localhost:8081
echo.
echo NAPOMENE:
echo - Za rad sa DVB karticama potreban je MuMuDVB
echo - Za descrambling potreban je OSCam
echo - Za skeniranje kanala potreban je w_scan
echo.
pause